import os

MONGODB_URL=os.getenv("MONGODB_URL","")
AWS_ACCESS_KEY=os.getenv("AWS_ACCESS_KEY","")
AWS_SECRET_KEY=os.getenv("AWS_SECRET_KEY","")
AWS_REGION=os.getenv("AWS_REGION","")
S3_BUCKET_NAME=os.getenv("S3_BUCKET_NAME","")
MONGO_DB_NAME=os.getenv("MONGO_DB_NAME","test")

LLAMA_PARSER_API=os.getenv("LLAMA_PARSER_API","")
PINECONE_API_KEY=os.getenv("PINECONE_API_KEY","")
PINECODNE_INDEX=os.getenv("PINECODNE_INDEX","")

SAGEMAKER_ACCESS_KEY=os.getenv("SAGEMAKER_ACCESS_KEY","")
SAGEMAKER_SECRET_KEY=os.getenv("SAGEMAKER_SECRET_KEY","")
SAGEMAKER_REGION=os.getenv("SAGEMAKER_REGION","")

