import os
MONGODB_URL=os.getenv("MONGODB_URL","")
AWS_ACCESS_KEY=os.getenv("AWS_ACCESS_KEY","")
AWS_SECRET_KEY=os.getenv("AWS_SECRET_KEY","")
AWS_REGION=os.getenv("AWS_REGION","")
S3_BUCKET_NAME=os.getenv("S3_BUCKET_NAME","")
MONGO_DB_NAME=os.getenv("MONGO_DB_NAME","")

INDEXING_LAMBDA_URL=os.getenv("INDEXING_LAMBDA_URL","")

PINECONE_API_KEY=os.getenv("PINECONE_API_KEY","")
PINECODNE_INDEX=os.getenv("PINECODNE_INDEX","")

SAGEMAKER_ACCESS_KEY=os.getenv("SAGEMAKER_ACCESS_KEY","")
SAGEMAKER_SECRET_KEY=os.getenv("SAGEMAKER_SECRET_KEY","")
SAGEMAKER_REGION=os.getenv("SAGEMAKER_REGION","us-east-1")
SAGEMAKER_ENDPOINT_NAME=os.getenv("SAGEMAKER_ENDPOINT_NAME","")

LAMBDA_ACCESS_KEY=os.getenv("LAMBDA_ACCESS_KEY","")
LAMBDA_SECRET_KEY=os.getenv("LAMBDA_SECRET_KEY","")
LAMBDA_REGION=os.getenv("LAMBDA_REGION","us-east-1")

COHER_API_KEY=os.getenv("COHER_API_KEY","")
OPEN_AI_KEY=os.getenv("OPEN_AI_KEY","")